### PR TITLE
replace hardcoded repo name in tests

### LINKED ISSUE #951: donejs/donejs hardcoded in the tests
These two files have this repo hard-coded, so submissions from forks fail:

- https://github.com/donejs/donejs/blob/b6879cbdd98d2665871f1f50173ecdc15dcc822e/guides/guide/test.js#L31
- https://github.com/donejs/donejs/blob/b6879cbdd98d2665871f1f50173ecdc15dcc822e/guides/place-my-order/test.js#L44

### PR DESCRIPTION
**Pull request by morrme**
Closes :  #951

### CODE REVIEW

File: guides/guide/test.js [hunk 1]
```diff
@@ -27,8 +27,9 @@ guide.step("Remove existing dependencies", function(){
 guide.step("Install donejs", function(){
   var branch = process.env.TRAVIS_PULL_REQUEST_BRANCH || process.env.TRAVIS_BRANCH
     || process.env.APPVEYOR_REPO_COMMIT || 'master';
+  var repo = process.env.TRAVIS_PULL_REQUEST_SLUG || process.env.TRAVIS_REPO_SLUG;
 
-	return guide.executeCommand("npm", ["install", "donejs/donejs#" + branch, "-g"]);
+	return guide.executeCommand("npm", ["install", repo + branch, "-g"]);
```
Comment (andrejewski) [inline guides/guide/test.js]: I think here and in the other changed test it should be `repo + '#' + branch` because the SLUG variables do not provide the `#` separator.

**Comment by morrme** [comment]
@andrejewski looks like that did it! thanks for the opportunity!

**Comment by phillipskevin** [comment]
Thanks @morrme for the contribution!

**Comment by morrme** [comment]
@phillipskevin Hi! & my pleasure!!!
