### PR TITLE
Fixes ToC on iOS Safari and Chrome.

### LINKED ISSUE #403: menu broken on ios Chrome
To reproduce, on an actual phone, open chrome to the features page or a guide.

Click one of the headers like "Performance Features". It seems to load something but the menu doesn't expand.

The + icon also doesn't do anything.

I can't reproduce this on a simulator or on Chrome desktop simulating ios.

### PR DESCRIPTION
**Pull request by Alfredo-Delgado**
Closes #403

Thanks for the help, @James0x57

### CODE REVIEW

File: docs/theme/static/static.js [hunk 1]
```diff
@@ -230,6 +230,7 @@ steal("./content_list.js",
         var scrollSpyCurrentH3 = $( "#scrollSpyCurrentH3" );
         var activeH2Li = $();
         var doJQCollapsing = $( "body.Guide, body.place-my-order, body.Apis" ).length ? true : false;
+        var isIOS = /iPad|iPhone|iPod/.test(navigator.platform);
```
Comment (moschel) [inline docs/theme/static/static.js]: what about iPad?

Comment (moschel) [inline docs/theme/static/static.js:233]: Is there a way to feature detect this?

**Comment by moschel** [comment]
Merging to fix the live problem, but let's talk about if there's a better way of not browser sniffing.
