### PR TITLE
Fixes #933. donejs help should no longer throw stack trace

### LINKED ISSUE #933: `donejs help` errors out when it was expected to return the command usage
__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

`donejs help` errors out with the following error:
```
Error: Could not find local DoneJS binary (/Users/mark/Projects/DoneJS/donejs/node_modules/.bin/donejs)
    at /Users/mark/Projects/DoneJS/donejs/lib/cli/run-binary.js:21:25
```

__Steps to reproduce:__

1. Open terminal
2. Assuming `donejs` is installed globally
3. Run `donejs help` -- watch the fireworks, where fireworks is a stack trace.

__Expected results:__

Expected the same results running `donejs` or `donejs -h`

__Actual results:__

```
Error: Could not find local DoneJS binary (/Users/mark/Projects/DoneJS/donejs/node_modules/.bin/donejs)
    at /Users/mark/.nvm/versions/node/v6.10.2/lib/node_modules/donejs/lib/cli/run-binary.js:21:25
    at _fulfilled (/Users/mark/.nvm/versions/node/v6.10.2/lib/node_modules/donejs/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/mark/.nvm/versions/node/v6.10.2/lib/node_modules/donejs/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/mark/.nvm/versions/node/v6.10.2/lib/node_modules/donejs/node_modules/q/q.js:816:13)
    at /Users/mark/.nvm/versions/node/v6.10.2/lib/node_modules/donejs/node_modules/q/q.js:877:14
    at runSingle (/Users/mark/.nvm/versions/node/v6.10.2/lib/node_modules/donejs/node_modules/q/q.js:137:13)
    at flush (/Users/mark/.nvm/versions/node/v6.10.2/lib/node_modules/donejs/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
```

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               | 1.0.0
| node -v                  | v6.10.2
| npm -v                   | 3.10.10
| Operating system | macOS Sierra (10.12.4)

### PR DESCRIPTION
**Pull request by mjstahl**
Fixes `donejs help` from throwing a stack trace.

### CODE REVIEW

File: lib/cli/index.js [hunk 1]
```diff
@@ -4,7 +4,6 @@ var runBinary = require('./run-binary');
 
 // commands
 var add = require('./cmd-add');
-var help = require('./cmd-help');
```
Comment (matthewp) [inline lib/cli/index.js]: I don't get it, we didn't need cmd-help?

**Comment by matthewp** [comment]
LGTM 👍

**Comment by matthewp** [comment]
Thanks!
